import React from "react";
import { motion } from "framer-motion";
import { Link } from "wouter";

const base = import.meta.env.BASE_URL;

const FadeIn = ({ children, delay = 0, className = "" }: { children: React.ReactNode; delay?: number; className?: string }) => (
  <motion.div
    initial={{ opacity: 0, y: 20 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ duration: 0.5, delay, ease: "easeOut" }}
    className={className}
  >
    {children}
  </motion.div>
);

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-3">
      <h2 className="text-lg font-bold text-[#42342c]">{title}</h2>
      <div className="space-y-2">{children}</div>
    </div>
  );
}

function SubHeading({ children }: { children: string }) {
  return (
    <p className="font-semibold text-[#42342c] text-sm mt-2">{children}</p>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <p className="text-sm text-[#897a72] leading-relaxed">{children}</p>
  );
}

function Bullet({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex gap-2 pl-1">
      <span className="text-sm text-[#897a72] shrink-0">•</span>
      <p className="text-sm text-[#897a72] leading-relaxed">{children}</p>
    </div>
  );
}

function ExternalLink({ label, url }: { label: string; url: string }) {
  return (
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
      className="text-sm font-semibold text-[#c53c5a] underline hover:opacity-80 transition-opacity"
    >
      {label}
    </a>
  );
}

function InlineLink({ label, url }: { label: string; url: string }) {
  return (
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
      className="font-semibold text-[#c53c5a] underline hover:opacity-80 transition-opacity"
    >
      {label}
    </a>
  );
}

export default function Privacy() {
  return (
    <div className="min-h-screen text-[#42342c]">

      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 p-4 flex justify-between items-center bg-[#f5f1e8]/90 backdrop-blur-md border-b border-[#897a72]/10">
        <Link href="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
          <img src={`${base}brand/icon.png`} alt="WeName App Icon" className="w-8 h-8 rounded-lg shadow-sm" />
          <span className="font-bold text-xl tracking-tight">WeName</span>
        </Link>
        <Link href="/" className="text-sm text-[#897a72] hover:text-[#42342c] transition-colors font-medium">
          ← Back to home
        </Link>
      </nav>

      {/* Main content */}
      <main className="pt-32 pb-24 px-6 max-w-2xl mx-auto">

        <FadeIn>
          <div className="text-center mb-12">
            <div className="inline-block px-4 py-1 rounded-full bg-[#3168a5]/10 text-[#3168a5] font-bold text-sm tracking-wide mb-4">
              LEGAL
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-4 text-[#42342c]">
              Privacy Policy
            </h1>
            <p className="text-base text-[#897a72]">Last updated May 27, 2026</p>
          </div>
        </FadeIn>

        <FadeIn delay={0.1}>
          <div className="bg-white/60 border border-[#897a72]/15 rounded-3xl p-8 shadow-sm space-y-8">

            <Section title="1. Introduction">
              <P>
                WeName ("we," "our," or "us") is a collaborative baby name discovery application that
                helps couples find the perfect name together. This Privacy Policy explains how we
                collect, use, store, and protect your personal information when you use our application
                and related services at wename.app.
              </P>
              <P>By using WeName, you agree to the practices described in this policy.</P>
            </Section>

            <Section title="2. Information We Collect">
              <SubHeading>Information You Provide Directly:</SubHeading>
              <Bullet>Your display name</Bullet>
              <Bullet>Your email address (when signing in or creating an account)</Bullet>
              <Bullet>Your baby's last name (optional, used only for personalized name suggestions)</Bullet>
              <Bullet>Your baby's gender preference (boy, girl, or either)</Bullet>

              <SubHeading>Information Generated by Your Use of the App:</SubHeading>
              <Bullet>Names you have liked or disliked (your swipe history)</Bullet>
              <Bullet>Names matched between you and your partner</Bullet>
              <Bullet>Your partner relationship (linked account)</Bullet>
              <Bullet>Invitation codes you create or use</Bullet>
              <Bullet>Daily usage activity counts</Bullet>

              <SubHeading>Information Collected Automatically:</SubHeading>
              <Bullet>Authentication tokens and session data managed by our backend provider</Bullet>
            </Section>

            <Section title="3. How We Use Your Information">
              <P>We use your information to:</P>
              <Bullet>Operate and provide the WeName service</Bullet>
              <Bullet>Match names you and your partner both like</Bullet>
              <Bullet>Generate AI-powered name suggestions personalized to your preferences</Bullet>
              <Bullet>Send you a magic link email when you choose to sign in without a password</Bullet>
              <Bullet>Manage your account and partner connection</Bullet>
              <Bullet>Enforce daily usage limits for free-tier accounts</Bullet>
              <Bullet>Improve the app over time</Bullet>
            </Section>

            <Section title="4. Information Shared with Third Parties">
              <P>
                We use the following third-party services to operate WeName. Each service receives only
                the minimum data necessary for its function.
              </P>

              <SubHeading>Supabase (Database and Authentication)</SubHeading>
              <P>
                Your profile, swipe history, matches, and partner data are stored securely in a
                Supabase PostgreSQL database located in the United States (East US - Ohio). Supabase
                processes data on our behalf under a data processing agreement.
              </P>
              <ExternalLink label="Privacy Policy" url="https://supabase.com/privacy" />

              <SubHeading>SendGrid (Email Delivery)</SubHeading>
              <P>
                When you request a magic link sign-in, your email address is sent to SendGrid solely
                to deliver the login email. No other personal information is shared with SendGrid.
              </P>
              <ExternalLink label="Privacy Policy" url="https://www.twilio.com/en-us/legal/privacy" />

              <SubHeading>OpenAI (AI Name Suggestions)</SubHeading>
              <P>
                When you request AI-powered name suggestions, we send OpenAI the following information:
                names you and your partner have liked, names you have matched on, your baby's gender
                preference, your style preference (classic, modern, or unique), and your baby's last
                name if you have provided one. This data is used solely to generate name suggestions.
                We do not send your name, email address, or account identifiers to OpenAI. We do not
                use your data to train our own AI models. OpenAI may process this data in accordance
                with their privacy policy.
              </P>
              <ExternalLink label="Privacy Policy" url="https://openai.com/policies/privacy-policy" />

              <SubHeading>Google and Apple (Sign-In)</SubHeading>
              <P>
                If you choose to sign in with Google or Apple, those services authenticate your
                identity and share your email address with us. We do not receive or store your
                password.
              </P>
              <ExternalLink label="Google Privacy Policy" url="https://policies.google.com/privacy" />
              <ExternalLink label="Apple Privacy Policy" url="https://www.apple.com/legal/privacy" />

              <SubHeading>Meta (Facebook) SDK — Ad Campaign Measurement</SubHeading>
              <P>
                WeName uses the Meta SDK (react-native-fbsdk-next) on iOS to measure the
                performance of our app install advertising campaigns. This SDK does not collect
                your name, email address, swipe history, partner data, or any other content you
                create in the app.
              </P>
              <P>What the Meta SDK transmits to Meta's servers:</P>
              <Bullet>A standard "app open" event each time you launch the app, used solely to attribute installs to ad campaigns</Bullet>
              <Bullet>Basic device context automatically attached to every event: app version, operating system version, device locale, and timezone</Bullet>
              <Bullet>A privacy-preserving SKAdNetwork attribution token, which Apple generates and manages on-device without exposing your identity</Bullet>
              <P>
                The Meta SDK does <strong>not</strong> collect your Advertising Identifier (IDFA)
                — we have disabled IDFA collection in our configuration. On iOS, Apple will ask
                your permission to track you before any cross-app tracking can occur. If you
                decline, the SDK still sends the anonymous app open event but does not associate
                it with you personally across other apps or websites. You can change this
                permission at any time in your iPhone's Settings → Privacy & Security → Tracking.
              </P>
              <ExternalLink label="Meta Privacy Policy" url="https://www.facebook.com/privacy/policy/" />

              <P>
                We do not sell or rent your personal information. The data shared with Meta is
                limited to anonymous campaign measurement signals and does not include any
                personally identifying content from your WeName account.
              </P>
            </Section>

            <Section title="5. Data Storage and Security">
              <P>
                Your data is stored in a Supabase database hosted in the United States (East US -
                Ohio), protected by Row-Level Security policies. This means users can only access
                their own data and the limited partner information required to display matches. All
                data is encrypted in transit using TLS and encrypted at rest.
              </P>
              <P>
                If you are located in the European Economic Area (EEA), please note that your data is
                transferred to and stored in the United States. We rely on Standard Contractual
                Clauses (SCCs) and Supabase's data processing agreements to ensure this transfer
                complies with GDPR requirements.
              </P>
            </Section>

            <Section title="6. Data Retention and Deletion">
              <P>We retain your account data for as long as your account is active.</P>
              <P>
                You may delete your account at any time from the Account section of the app. When you
                delete your account, all of your personal data — including your profile, swipe history,
                matches, and partner data — is permanently and immediately deleted from our systems.
              </P>
              <P>
                Some limited technical logs and backups may persist temporarily for security and
                reliability purposes but are not accessible to users and are automatically deleted
                over time.
              </P>
            </Section>

            <Section title="7. Your Rights Under GDPR (EEA Users)">
              <P>
                If you are located in the European Economic Area, you have the following rights under
                the General Data Protection Regulation (GDPR):
              </P>
              <Bullet>Right of Access — You may request a copy of the personal data we hold about you.</Bullet>
              <Bullet>Right to Rectification — You may request that we correct any inaccurate or incomplete data.</Bullet>
              <Bullet>Right to Erasure — You may request deletion of your personal data. You can do this directly by deleting your account in the app, or by contacting us.</Bullet>
              <Bullet>Right to Restriction — You may request that we restrict processing of your data in certain circumstances.</Bullet>
              <Bullet>Right to Data Portability — You may request that we provide your data in a structured, machine-readable format.</Bullet>
              <Bullet>Right to Object — You may object to certain types of processing, including processing based on legitimate interests.</Bullet>
              <Bullet>Right to Withdraw Consent — Where processing is based on your consent, you may withdraw it at any time without affecting the lawfulness of prior processing.</Bullet>

              <SubHeading>Lawful Bases for Processing:</SubHeading>
              <Bullet>Performance of a contract — Processing necessary to operate your account and provide the WeName service.</Bullet>
              <Bullet>Consent — For optional features such as AI-powered name suggestions.</Bullet>
              <Bullet>Legitimate interests — For app security, fraud prevention, and service improvement, where these interests are not overridden by your rights.</Bullet>

              <P>
                To exercise any of your rights, contact us at{" "}
                <InlineLink label="wenameapp@gmail.com" url="mailto:wenameapp@gmail.com" />
                . We will respond to your request within 30 days.
              </P>
              <P>
                If you believe we have not handled your data appropriately, you have the right to
                lodge a complaint with your local data protection authority. In Canada (where our
                company is based), the relevant authority is the Office of the Privacy Commissioner of
                Canada (OPC):{" "}
                <InlineLink label="priv.gc.ca" url="https://www.priv.gc.ca" />
              </P>
            </Section>

            <Section title="8. Children's Privacy">
              <P>
                WeName is intended for users aged 13 and older. Our service is not directed at
                children under 13, and we do not knowingly collect personal information from children
                under 13. If you believe a child under 13 has created an account or provided us with
                personal information, please contact us immediately at{" "}
                <InlineLink label="wenameapp@gmail.com" url="mailto:wenameapp@gmail.com" />{" "}
                so we can promptly delete the information.
              </P>
            </Section>

            <Section title="9. Cookies and Local Storage">
              <P>
                WeName uses browser local storage to remember your session, onboarding status, and
                user ID between visits. We do not use advertising cookies or tracking pixels on this
                website. The WeName iOS app uses the Meta SDK for app install measurement as
                described in Section 4 above.
              </P>
            </Section>

            <Section title="10. Changes to This Policy">
              <P>
                We may update this Privacy Policy from time to time. When we do, we will update the
                "Last Updated" date at the top of this policy. For any material changes, we will
                notify you directly through an in-app notification the next time you open the app.
              </P>
            </Section>

            <Section title="11. Contact Us">
              <P>
                If you have questions, concerns, or requests related to this Privacy Policy or how we
                handle your data, you may contact us at:
              </P>
              <P>Christopher Steeves (WeName){"\n"}Ottawa, Ontario, Canada</P>
              <ExternalLink label="wenameapp@gmail.com" url="mailto:wenameapp@gmail.com" />
              <ExternalLink label="wename.app" url="https://wename.app" />
            </Section>

          </div>
        </FadeIn>
      </main>

      {/* Footer */}
      <footer className="border-t border-[#897a72]/20 px-6 py-6">
        <div className="max-w-2xl mx-auto flex flex-col md:flex-row justify-between items-center text-sm text-[#897a72] gap-4">
          <p>Made for couples choosing a name together.</p>
          <div className="flex gap-4">
            <Link href="/privacy" className="text-[#42342c] font-medium">Privacy Policy</Link>
            <Link href="/terms" className="hover:text-[#42342c] transition-colors">Terms</Link>
            <Link href="/support" className="hover:text-[#42342c] transition-colors">Support</Link>
          </div>
        </div>
      </footer>

    </div>
  );
}
