import * as Linking from "expo-linking";
import React from "react";
import {
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { SubPageHeader } from "@/components/SubPageHeader";
import { fonts } from "@/constants/fonts";
import { useColors } from "@/hooks/useColors";

export default function PrivacyPolicyScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();

  return (
    <View style={{ flex: 1, backgroundColor: colors.parchment }}>
      <SubPageHeader title="Privacy Policy" subtitle="Last updated April 15, 2026" />
      <ScrollView
        contentContainerStyle={{
          padding: 20,
          paddingBottom: insets.bottom + 40,
          gap: 20,
        }}
      >
        <Section title="1. Introduction" colors={colors}>
          <P colors={colors}>
            WeName ("we," "our," or "us") is a collaborative baby name discovery application that
            helps couples find the perfect name together. This Privacy Policy explains how we
            collect, use, store, and protect your personal information when you use our application
            and related services at wename.app.
          </P>
          <P colors={colors}>By using WeName, you agree to the practices described in this policy.</P>
        </Section>

        <Section title="2. Information We Collect" colors={colors}>
          <SubHeading colors={colors}>Information You Provide Directly:</SubHeading>
          <Bullet colors={colors}>Your display name</Bullet>
          <Bullet colors={colors}>Your email address (when signing in or creating an account)</Bullet>
          <Bullet colors={colors}>
            Your baby's last name (optional, used only for personalized name suggestions)
          </Bullet>
          <Bullet colors={colors}>Your baby's gender preference (boy, girl, or either)</Bullet>

          <SubHeading colors={colors}>Information Generated by Your Use of the App:</SubHeading>
          <Bullet colors={colors}>Names you have liked or disliked (your swipe history)</Bullet>
          <Bullet colors={colors}>Names matched between you and your partner</Bullet>
          <Bullet colors={colors}>Your partner relationship (linked account)</Bullet>
          <Bullet colors={colors}>Invitation codes you create or use</Bullet>
          <Bullet colors={colors}>Daily usage activity counts</Bullet>

          <SubHeading colors={colors}>Information Collected Automatically:</SubHeading>
          <Bullet colors={colors}>
            Authentication tokens and session data managed by our backend provider
          </Bullet>
        </Section>

        <Section title="3. How We Use Your Information" colors={colors}>
          <P colors={colors}>We use your information to:</P>
          <Bullet colors={colors}>Operate and provide the WeName service</Bullet>
          <Bullet colors={colors}>Match names you and your partner both like</Bullet>
          <Bullet colors={colors}>
            Generate AI-powered name suggestions personalized to your preferences
          </Bullet>
          <Bullet colors={colors}>
            Send you a magic link email when you choose to sign in without a password
          </Bullet>
          <Bullet colors={colors}>Manage your account and partner connection</Bullet>
          <Bullet colors={colors}>Enforce daily usage limits for free-tier accounts</Bullet>
          <Bullet colors={colors}>Improve the app over time</Bullet>
        </Section>

        <Section title="4. Information Shared with Third Parties" colors={colors}>
          <P colors={colors}>
            We use the following third-party services to operate WeName. Each service receives only
            the minimum data necessary for its function.
          </P>

          <SubHeading colors={colors}>Supabase (Database and Authentication)</SubHeading>
          <P colors={colors}>
            Your profile, swipe history, matches, and partner data are stored securely in a
            Supabase PostgreSQL database located in the United States (East US - Ohio). Supabase
            processes data on our behalf under a data processing agreement.
          </P>
          <LinkRow colors={colors} label="Privacy Policy" url="https://supabase.com/privacy" />

          <SubHeading colors={colors}>SendGrid (Email Delivery)</SubHeading>
          <P colors={colors}>
            When you request a magic link sign-in, your email address is sent to SendGrid solely
            to deliver the login email. No other personal information is shared with SendGrid.
          </P>
          <LinkRow
            colors={colors}
            label="Privacy Policy"
            url="https://www.twilio.com/en-us/legal/privacy"
          />

          <SubHeading colors={colors}>OpenAI (AI Name Suggestions)</SubHeading>
          <P colors={colors}>
            When you request AI-powered name suggestions, we send OpenAI the following information:
            names you and your partner have liked, names you have matched on, your baby's gender
            preference, your style preference (classic, modern, or unique), and your baby's last
            name if you have provided one. This data is used solely to generate name suggestions.
            We do not send your name, email address, or account identifiers to OpenAI. We do not
            use your data to train our own AI models. OpenAI may process this data in accordance
            with their privacy policy.
          </P>
          <LinkRow
            colors={colors}
            label="Privacy Policy"
            url="https://openai.com/policies/privacy-policy"
          />

          <SubHeading colors={colors}>Google and Apple (Sign-In)</SubHeading>
          <P colors={colors}>
            If you choose to sign in with Google or Apple, those services authenticate your
            identity and share your email address with us. We do not receive or store your
            password.
          </P>
          <LinkRow
            colors={colors}
            label="Google Privacy Policy"
            url="https://policies.google.com/privacy"
          />
          <LinkRow
            colors={colors}
            label="Apple Privacy Policy"
            url="https://www.apple.com/legal/privacy"
          />

          <P colors={colors}>
            We do not sell, rent, or share your personal information with third parties for
            advertising or marketing purposes.
          </P>
        </Section>

        <Section title="5. Data Storage and Security" colors={colors}>
          <P colors={colors}>
            Your data is stored in a Supabase database hosted in the United States (East US -
            Ohio), protected by Row-Level Security policies. This means users can only access
            their own data and the limited partner information required to display matches. All
            data is encrypted in transit using TLS and encrypted at rest.
          </P>
          <P colors={colors}>
            If you are located in the European Economic Area (EEA), please note that your data is
            transferred to and stored in the United States. We rely on Standard Contractual
            Clauses (SCCs) and Supabase's data processing agreements to ensure this transfer
            complies with GDPR requirements.
          </P>
        </Section>

        <Section title="6. Data Retention and Deletion" colors={colors}>
          <P colors={colors}>
            We retain your account data for as long as your account is active.
          </P>
          <P colors={colors}>
            You may delete your account at any time from the Account section of the app. When you
            delete your account, all of your personal data — including your profile, swipe history,
            matches, and partner data — is permanently and immediately deleted from our systems.
          </P>
          <P colors={colors}>
            Some limited technical logs and backups may persist temporarily for security and
            reliability purposes but are not accessible to users and are automatically deleted
            over time.
          </P>
        </Section>

        <Section title="7. Your Rights Under GDPR (EEA Users)" colors={colors}>
          <P colors={colors}>
            If you are located in the European Economic Area, you have the following rights under
            the General Data Protection Regulation (GDPR):
          </P>
          <Bullet colors={colors}>
            Right of Access — You may request a copy of the personal data we hold about you.
          </Bullet>
          <Bullet colors={colors}>
            Right to Rectification — You may request that we correct any inaccurate or incomplete
            data.
          </Bullet>
          <Bullet colors={colors}>
            Right to Erasure — You may request deletion of your personal data. You can do this
            directly by deleting your account in the app, or by contacting us.
          </Bullet>
          <Bullet colors={colors}>
            Right to Restriction — You may request that we restrict processing of your data in
            certain circumstances.
          </Bullet>
          <Bullet colors={colors}>
            Right to Data Portability — You may request that we provide your data in a structured,
            machine-readable format.
          </Bullet>
          <Bullet colors={colors}>
            Right to Object — You may object to certain types of processing, including processing
            based on legitimate interests.
          </Bullet>
          <Bullet colors={colors}>
            Right to Withdraw Consent — Where processing is based on your consent, you may
            withdraw it at any time without affecting the lawfulness of prior processing.
          </Bullet>

          <SubHeading colors={colors}>Lawful Bases for Processing:</SubHeading>
          <Bullet colors={colors}>
            Performance of a contract — Processing necessary to operate your account and provide
            the WeName service.
          </Bullet>
          <Bullet colors={colors}>
            Consent — For optional features such as AI-powered name suggestions.
          </Bullet>
          <Bullet colors={colors}>
            Legitimate interests — For app security, fraud prevention, and service improvement,
            where these interests are not overridden by your rights.
          </Bullet>

          <P colors={colors}>
            To exercise any of your rights, contact us at{" "}
            <InlineLink
              colors={colors}
              label="wenameapp@gmail.com"
              url="mailto:wenameapp@gmail.com"
            />
            . We will respond to your request within 30 days.
          </P>
          <P colors={colors}>
            If you believe we have not handled your data appropriately, you have the right to
            lodge a complaint with your local data protection authority. In Canada (where our
            company is based), the relevant authority is the Office of the Privacy Commissioner of
            Canada (OPC):{" "}
            <InlineLink
              colors={colors}
              label="priv.gc.ca"
              url="https://www.priv.gc.ca"
            />
          </P>
        </Section>

        <Section title="8. Children's Privacy" colors={colors}>
          <P colors={colors}>
            WeName is intended for users aged 13 and older. Our service is not directed at
            children under 13, and we do not knowingly collect personal information from children
            under 13. If you believe a child under 13 has created an account or provided us with
            personal information, please contact us immediately at{" "}
            <InlineLink
              colors={colors}
              label="wenameapp@gmail.com"
              url="mailto:wenameapp@gmail.com"
            />{" "}
            so we can promptly delete the information.
          </P>
        </Section>

        <Section title="9. Cookies and Local Storage" colors={colors}>
          <P colors={colors}>
            WeName uses browser local storage to remember your session, onboarding status, and
            user ID between visits. We do not use advertising cookies, tracking pixels, or any
            third-party analytics services.
          </P>
        </Section>

        <Section title="10. Changes to This Policy" colors={colors}>
          <P colors={colors}>
            We may update this Privacy Policy from time to time. When we do, we will update the
            "Last Updated" date at the top of this policy. For any material changes, we will
            notify you directly through an in-app notification the next time you open the app.
          </P>
        </Section>

        <Section title="11. Contact Us" colors={colors}>
          <P colors={colors}>
            If you have questions, concerns, or requests related to this Privacy Policy or how we
            handle your data, you may contact us at:
          </P>
          <P colors={colors}>Christopher Steeves (WeName){"\n"}Ottawa, Ontario, Canada</P>
          <LinkRow colors={colors} label="wenameapp@gmail.com" url="mailto:wenameapp@gmail.com" />
          <LinkRow colors={colors} label="wename.app" url="https://wename.app" />
        </Section>
      </ScrollView>
    </View>
  );
}

function Section({
  title,
  colors,
  children,
}: {
  title: string;
  colors: ReturnType<typeof useColors>;
  children: React.ReactNode;
}) {
  return (
    <View style={styles.section}>
      <Text
        style={[
          styles.sectionTitle,
          { fontFamily: fonts.displayBold, color: colors.foreground },
        ]}
      >
        {title}
      </Text>
      <View style={{ gap: 8 }}>{children}</View>
    </View>
  );
}

function SubHeading({
  colors,
  children,
}: {
  colors: ReturnType<typeof useColors>;
  children: string;
}) {
  return (
    <Text
      style={{
        fontFamily: fonts.displaySemibold,
        fontSize: 13,
        color: colors.foreground,
        marginTop: 4,
      }}
    >
      {children}
    </Text>
  );
}

function P({
  colors,
  children,
}: {
  colors: ReturnType<typeof useColors>;
  children: React.ReactNode;
}) {
  return (
    <Text
      style={{
        fontFamily: fonts.display,
        fontSize: 14,
        lineHeight: 22,
        color: colors.mutedForeground,
      }}
    >
      {children}
    </Text>
  );
}

function Bullet({
  colors,
  children,
}: {
  colors: ReturnType<typeof useColors>;
  children: string;
}) {
  return (
    <View style={{ flexDirection: "row", gap: 8, paddingLeft: 4 }}>
      <Text
        style={{
          fontFamily: fonts.display,
          fontSize: 14,
          lineHeight: 22,
          color: colors.mutedForeground,
        }}
      >
        {"•"}
      </Text>
      <Text
        style={{
          flex: 1,
          fontFamily: fonts.display,
          fontSize: 14,
          lineHeight: 22,
          color: colors.mutedForeground,
        }}
      >
        {children}
      </Text>
    </View>
  );
}

function LinkRow({
  colors,
  label,
  url,
}: {
  colors: ReturnType<typeof useColors>;
  label: string;
  url: string;
}) {
  return (
    <Pressable onPress={() => Linking.openURL(url)}>
      <Text
        style={{
          fontFamily: fonts.displaySemibold,
          fontSize: 14,
          color: colors.rose,
          textDecorationLine: "underline",
        }}
      >
        {label}
      </Text>
    </Pressable>
  );
}

function InlineLink({
  colors,
  label,
  url,
}: {
  colors: ReturnType<typeof useColors>;
  label: string;
  url: string;
}) {
  return (
    <Text
      onPress={() => Linking.openURL(url)}
      style={{
        fontFamily: fonts.displaySemibold,
        fontSize: 14,
        color: colors.rose,
        textDecorationLine: "underline",
      }}
    >
      {label}
    </Text>
  );
}

const styles = StyleSheet.create({
  section: {
    gap: 10,
  },
  sectionTitle: {
    fontSize: 16,
    marginBottom: 2,
  },
});
