// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/paywall/Celestial.tsx": () => import("../components/mockups/paywall/Celestial.tsx"),
  "./components/mockups/paywall/Editorial.tsx": () => import("../components/mockups/paywall/Editorial.tsx"),
  "./components/mockups/paywall/Garden.tsx": () => import("../components/mockups/paywall/Garden.tsx")
};
